### ISSUE TITLE
Remove dependency on custom Napari

### ISSUE THREAD

**Issue by vigji** [portugueslab/sashimi#100]
Relying on a custom Napari viewer (and only for removing a coloured frame) sounds like a bad idea for package management @diegoasua

**Comment by diegoasua** [comment]
Unfortunately I couldn't find a way to patch the coloured frame. Maybe I will open a question to napari developers and ask them how to include this dictionary in the native napari

**Comment by vigji** [comment]
Have you tried setting directly         `viewer._qt_window.setStyleSheet(...)` or something like that?

**Comment by diegoasua** [comment]
That is a great suggestion Luigi! Indeed there was a way to set this through that function... I wonder how I didn't think of this before. I will therefore close this issue and remove our napari fork
