### ISSUE TITLE
Have a reasonable preview of fake waveform (or just a flat line) for testing scanning without hardware

### ISSUE THREAD

**Issue by vilim** [portugueslab/sashimi#111]

**Comment by diegoasua** [comment]
I have implemented  a flat line for now in #112 , happy to make it more realistic. Is there any kernel you had in mind to convolute the waveform to the fake-pulse response? I have dig a bit this but have not found satisfactory answers.

**Comment by vilim** [comment]
The issue is not the pulse response, but the time-shift that takes into account the periodicity (you have to make an additional circular buffer with the same period as the control period (which is not something sent to the hardware) and read from the corresponding section)
