### ISSUE TITLE
Adjust to new Napari schemes

### ISSUE THREAD

**Issue by diegoasua** [portugueslab/sashimi#118]

**Comment by vilim** [comment]
@diegoasua please elaborate

**Comment by diegoasua** [comment]
The inner structure of Napari has changed substantially since we wrapped sashimi around it. We access its widgets through dirty monkey patching, due to Napari's philosophy being that external functionality should be added to their platform as pluggins, instead of building a whole software around the viewer (like we do). So it is possible that with new releases of napari their inner structure has become more clear and therefore we may address that in our code by accessing their widgets in less monkey-patchy way. To be clear, I am not suggesting redoing the GUI as pluggins for napari - if that was scaring anyone - I think that would be a fool use of our time now.

**Comment by vigji** [comment]
Napari plugins hooks are still offering only hooks for file I/O,  so that is not on the table. Not sure the structure has changed in a more exposed way, this should be something very quick to look into

**Comment by diegoasua** [comment]
Found nothing new. Closing this.
