### ISSUE TITLE
Environment file dependencies outdated

### ISSUE THREAD

**Issue by fedem-p** [portugueslab/sashimi#134]
Bug ->  sashimi doesn't install following the described installation procedure:

## to reproduce the error:

- create env from environment file
- activate new env
- install pyvista and pyvista-py
- pip install .

## error msg:
Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.38.0
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by diegoasua** [comment]
[llvmlite](https://github.com/numba/llvmlite) is a dependency of numba used to accelerate some loops in the `Scanner`. It seems that installation fails because the manager is afraid of removing it. This is likely happening because numba is installed twice during this process, one [here](https://github.com/portugueslab/sashimi/blob/master/environment.yml) and then again [here](https://github.com/portugueslab/sashimi/blob/master/requirements.txt). The difference is that packages in the first file are managed by `conda`and the second by `pip`. Can you repeat the whole process in a clean environment after removing numba from the `requirements.txt`?

**Comment by fedem-p** [comment]
> [llvmlite](https://github.com/numba/llvmlite) is a dependency of numba. It seems that installation fails because the manager is afraid of removing it. This is likely happening because numba is installed twice during this process, once [here](https://github.com/portugueslab/sashimi/blob/master/environment.yml) and then again [here](https://github.com/portugueslab/sashimi/blob/master/requirements.txt). The difference is that packages in the first file are managed by `conda`and the second by `pip`. Can you repeat the whole process in a clean environment after removing numba from `requirements.txt`?

Thanks! 
I'll try again and see if that solves it, I haven't though about that!

**Comment by fedem-p** [comment]
@diegoasua Sorry for the long delay, 
I tried removing it from the req.txt but that doesn't solve the problem since when installing sashimi pip tries to re-install the correct version of llvmlite.

Also removing it from the req.txt file doesn't seem to be a great solution in my opinion since some users may prefer using their environment and install the dependencies from this file.

As such the solution I suggest - see PR #135 - is to specify the correct version both in the env file and in the req file.
Let me know what you think about it!

**Comment by diegoasua** [comment]
I can't reproduce your error. Please provide the`conda`, `pip` and `python` versions you used.

I have seen the PR. I am not in favor of locking a llvmlite version. Locking numba version is ok though.

**Comment by fedem-p** [comment]
to reproduce the error:

I have conda 4.10.3 

I run the following commands:

```
conda env create -f environment.yml
conda activate sashimi
pip install pyvisa
pip install pyvisa-py
pip install .
```

I have nothing against locking Numba version, I'll test both that and updating my conda version

**Comment by diegoasua** [comment]
Thanks for the report @fedem-p. If locking numba works then it's all good for me and we can move this to your PR #135

**Comment by fedem-p** [comment]
Thanks @diegoasua for your suggestions and supervision :)
