### ISSUE TITLE
Stack jump when changing destination

### ISSUE THREAD

**Issue by vigji** [portugueslab/sashimi#65]
Funny bug: after setting the stack, if I select a new folder as the destination in "Saving", the displayed stack get circularily permuted in z. Going to calibration and back fixes it.

**Comment by diegoasua** [comment]
Is this still an issue?

**Comment by vigji** [comment]
yes it is!

**Comment by vigji** [comment]
Actually, I just had an outdid version on the ls computer. Seems to be fixed now, yes!
