### ISSUE TITLE
funny lag issue 

### ISSUE THREAD

**Issue by hlavian** [portugueslab/sashimi#75]
Noticed one small issue in the beautiful Sashimi program: I get a 27 seconds lag when changing number of planes in volumetric mode and when switching between calibration mode and volumetric mode.  This happens when the acquisition parameters are quite standard (3 volumes/sec, 15 planes, 2 skipped, exposure of 12 ms, ROI: 300x400 pixels). I attached a file of the settings used. 

I am using master branch at commit: a9ac885.

[200730 164103.txt](https://github.com/portugueslab/sashimi/files/5001990/200730.164103.txt)

**Comment by vilim** [comment]
The lag is when previewing things, not running the experiment, from what I understand? Anyway 27 seconds is horrible, the lag on changing settings should be at most the time it takes to acquire two full volumes. How did you determine the lag?

**Comment by hlavian** [comment]
Yes, the lag is when previewing, but also appeared when I first ran the experiment (everything was lagged: acquisition + activation of the stytra protocol). I just measured it in a very non-fancy way, with a stopwatch on my phone.

**Comment by vilim** [comment]
very curious. it will be tough to investigate without being at the scope, and I am not in Munich until next Friday. Does this problem appear randomly or every time you run the program? If stytra and acquisition start are lagged by exactly the same amount, one can still (painfully) do the experiments. I will check the changes since I left the program and there was no lag and the commit you are using.

**Comment by hlavian** [comment]
Oh don't worry about it, I am still running experiments. This was basically Luigi teaching me to use GitHub issues, it can definitely wait.

**Comment by hlavian** [comment]
An update on this: in following experiments I didn't get this delay most of the time

**Comment by diegoasua** [comment]
This could have been if the software crashed the first day previously to your experiment and some unkilled processes were running there somehow the software still managed to work but it was buggy. It can also be something from the code but it is weird that this only happens sometimes. I will actually be happy if this is seen again in the future as it means at least is something we can solve :)
