### ISSUE TITLE
docstrings style

### ISSUE THREAD

**Issue by vigji** [portugueslab/sashimi#77]
As I would start adding some to try understand all while I add tests.
Any preferences? I saw just a couple of docstrings already there in rst format, but I would prefer numpy or google style.

**Comment by vilim** [comment]
I personally don't care. Best to be consistent with the new lab packages (bouter etc), whatever we have decided for that

**Comment by diegoasua** [comment]
Afaik [Google and numpy formats are really similar](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/#:~:text=Google%20vs%20NumPy&text=NumPy%20style%20tends%20to%20require,long%20and%20in%2Ddepth%20docstrings.&text=Example%20NumPy%20Style%20Python%20Docstrings). I would go nevertheless for [Google](https://google.github.io/styleguide/pyguide.html) as we want to keep docs short and simple. As Vilim points out as far as docs are consistant we are good

**Comment by vigji** [comment]
Ok, numpy for consistency then!
