### ISSUE TITLE
Numpy-style doc generation and convention

### ISSUE THREAD

**Issue by diegoasua** [portugueslab/sashimi#95]
I have a little issue and a question:

1. I am unable to generate locally an `.html` docs file with `sphinx`. Running

```
$ sphinx-apidoc ../sashimi -o source/
$ make html
```

 in `..\docs` throws an error after the second command:

```
Running Sphinx v3.2.1

Extension error:
Could not import extension myst_parser (exception: No module named 'myst_parser')
```

2. It is not clear to me, regarding numpydoc docstring conventions, whether methods of the classes are documented below the method name or just [below the class itself](https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring)

**Comment by diegoasua** [comment]
**Update: I fixed the issue below running:**

```python
pip install myst-parser
```

**Comment by vigji** [comment]
that was indeed the solution! Can I close?

**Comment by diegoasua** [comment]
My question (2.) is still left to be answered 💣

**Comment by vigji** [comment]
They should for sure be documented as functions are. We can decide for the main classes (eg interface abstract classes) to also have the methods section as a summary in the class header.

**Comment by diegoasua** [comment]
Ok thanks. Then I close this.
