### ISSUE TITLE
Unify config keys with command line entries

### ISSUE THREAD

**Issue by diegoasua** [portugueslab/sashimi#96]
`--scanless` and `--scopeless` options for launching from command line modify certain `config.py` hardware keys so that mock objects are used instead of actual configured software.

As @vilim [pointed out](https://github.com/portugueslab/sashimi/pull/92#discussion_r493909489) every time one of this modes is called the hardware gets deconfigured. I like the idea of having these two modes (already in place), plus a third one `--triggerless` which will make the software run without the need of an external trigger and that allows to input experiment duration manually (it can be done just by using `MockComm` and enabling a GUI widget that actually sets duration). This third mode will resolve #68.

It is however quite clear that modifying hardware configuration is not the way to go. @vilim suggests two ad-hoc systems that could possible replace the current disposition. A simpler - though dirtier - fix would be to have respective keys in `config.py` which are then checked every time one of the hardware objects are called thorugh a wrapper function like the following:

```python

from sashimi.config import read_config

conf = read_config()

def absent_check(hardware_class_name: str, hardware_class_dict: dict):
    if conf["scopeless"]:
        return hardware_class_dict["mock"]()
    if conf["scanless"]:
        if hardware_class_name == "scanning":
            return hardware_class_dict["mock"]()
    if conf["trigerless"]:
        if hardware_class == "external_comm":
            return hardware_class_dict["mock"]()
    else:
        return None
```

These could be called as:

```python
self.hardware_class = absent_check(hardware_class_name, hardware_class_dict)
if self.hardware_class == None:
    self.hardware_class = hardware_class(...)
```

for each piece of hardware. Plus other nuances like disabling GUI widgets in certain modes, whcih would also by accomplished by checking for these keys.

Note aside: Of course one should ensure in `main.py` that at the begging of the script all these keys are set to `False` unless specified as an option in the cmd entry sequence.

Edit: Even cooler,  have this wrapper function as a custom decorator for each hardware class.

**Comment by vilim** [comment]
In general I am against these --*less options, instead having a systematic option schema for each piece of hardware that can be `mock`, `none`, or one of the real options. The `--trigerless` option is something that should be present in the GUI (so you can e.g. run an 'anatomy' without restarting the program. A checkbox and an input will do (a similar thing is implemented in the 2p).

The option system should run in such a way that it loads the config from file, and then updates all relevant parts present in the command line arguments (I would say something along the lines how modify-config works now)

**Comment by vilim** [comment]
(and the config system can be factored out to scopecuisine and hopefully implemented in the 2p, if anyone e.g. @EmanPaoli decides to work on it a bit more)

**Comment by diegoasua** [comment]
>In general I am against these --*less options, instead having a systematic option schema for each piece of hardware that can be mock, none, or one of the real options.

The --*less option is compatible with `mock`, `none`, `foo`. One could either set them through `sashimi-config` permanently or launch a run with specific settings through `sashimi --*less`.

> The --trigerless option is something that should be present in the GUI (so you can e.g. run an 'anatomy' without restarting the program. A checkbox and an input will do (a similar thing is implemented in the 2p).

The `--trigerless` option can coexist with the GUI in-built checkbox for triggerless acquisition. There is no necessarily a conflict between the two of them if this is well designed.

> The option system should run in such a way that it loads the config from file, and then updates all relevant parts present in the command line arguments (I would say something along the lines how modify-config works now)

How is this different from the current state of the entry level?

**Comment by vilim** [comment]
So ideally this would be the only way to sashimi:
```
sashimi --hardware.camera.type mock --hardware.scanning.type none
```
excatly mirroring the config file.
and everything else not set would be taken from the configuration. Now I am thinking this this is something that lightparam could provide (trough extending the ParamterTree class).
and this would exactly mirror the config structure.
In Stytra we also had these tension between the GUI, command line and config file parameters, and it was never resolved to my satisfaction. 
To run sashimi without stytra connection it would be
```
sashimi --comms.type none
```
and then the GUI would not even show you the checkbox.
(I would call it comms, because triggering is also camera)

But basically you want to avoid writing all these ifs for --*less cases, and handle it in the same way as the config.

**Comment by diegoasua** [comment]
This would unconstrain the launch from a set of fixed options. I like it. Now, how would we avoid deconfiguring `.sashimi\config.py`? Because current settings (i.e. a record of settings used in this launch) should be stored in another `.toml` or equivalent file? Or somehow maintained in memory but not modifying the config file like it is now

**Comment by vilim** [comment]
Yes exactly, maybe there would be one additional fixed option, --update-config which would write the command line-updated settings also to the file, but by default not.

**Comment by vigji** [comment]
I think we are all agreeing on having only either the full run or the mock one by now - hardware debugging can easily be done via tinkering with the config file, it's not such a big deal and potentially even less painful than figuring out cmd commands and specifying them every time. Would close this!
